name: Bournemouth Properties
favicon: null
layout_spectrum: 0.49106
typography_spectrum: 0.51043
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00adef'
    - '#231f20'
    - '#6a6869'
    - '#acabab'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
